# Do not edit this file directly. It has been autogenerated from
# example_discover_gateway_async.py

# Notes:
# 1 Before running the example, install the 'pystudernext' library locally:
#   - Open a command prompt at the root of this project
#   - run: pip install -e .    (or python -m pip install -e .)
#

import asyncio
import logging
import sys

from datetime import datetime

from pystudernext import AsyncNextDiscover, NextDiscover
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    # Discover IP address of Next Gateway
    # Can be usefull to provide a link to the Next Gateway Web Config
    url = NextDiscover.discover_gateway_webconfig()
    if url:
        logger.info(f"Next-Gateway Web Config found at: {url}")
    else:
        logger.info(f"Next-Gateway Web Config not found")


RunHelper.run(main)  # main loop
