# Do not edit this file directly. It has been autogenerated from
# example_discover_devices_async.py
import asyncio
from dataclasses import asdict
import logging
import sys

from pystudernext import AsyncNextApi, NextApi
from pystudernext import AsyncNextDiscover, NextDiscover
from pystudernext import AsyncNextFactory, NextFactory
from pystudernext import NextDataset
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    api = AsyncNextApi(server="192.186.1.50", port=502)    # port number configured in Xcom-LAN/Moxa NPort
    dataset = NextFactory.create_dataset()

    try:
        if not api.start():
            logger.info(f"Did not connect to Xcom")
            return
        
        helper = AsyncNextDiscover(api, dataset)

        # Discover NX Gateway info
        gw_info = helper.discover_gateway_info()

        logger.info(f"\n\n")
        logger.info(f"Discovered {gw_info}")

        # Discover NX devices
        devices = helper.discover_devices(getExtendedInfo=True, verbose=False)

        logger.info(f"\n\n")
        for device in devices:
            logger.info(f"Discovered {device}")

        # Log diagnostic information
        diag = api.get_diagnostics()
        logger.info(f"Diagnostics: {diag}")

    finally:
        api.stop()
        dataset = None


RunHelper.run(main)  # main loop
