# Do not edit this file directly. It has been autogenerated from
# example_discover_gateway_async.py
import asyncio
import logging
import sys

from datetime import datetime

from pystudernext import AsyncNextDiscover, NextDiscover
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    # Discover IP address of Next-LAN / Moxa
    # Can be usefull to open the Moxa NPort Web Config
    url = NextDiscover.discover_gateway_webconfig()
    if url:
        logger.info(f"NX Gateway Web Config found at: {url}")
    else:
        logger.info(f"NX Gateway Web Config not found")


RunHelper.run(main)  # main loop
