# Do not edit this file directly. It has been autogenerated from
# tests\test_datapoints_async.py
import pytest
import pytest_asyncio

from pystudernext import (
    NextDataset, 
    NextFormat, 
    NextDatapointUnknownException,
    AsyncNextFactory,
    NextFactory,
)


@pytest.mark.parametrize(
    "exp_len",
    [
        (190),
    ]
)
def test_create(exp_len):
    dataset = NextFactory.create_dataset()    

    assert len(dataset._datapoints) == exp_len


def test_address():
    dataset = NextFactory.create_dataset()

    param = dataset.get_by_address(6900)
    assert param.family_id == "nx3"
    assert param.address == 6900
    assert param.format == NextFormat.FLOAT

    param = dataset.get_by_address(5100)
    assert param.family_id == "nx3"
    assert param.address == 5100
    assert param.format == NextFormat.ENUM
    assert param.options != None
    assert type(param.options) is dict
    assert len(param.options) == 4

    param = dataset.get_by_address(6900, "nx3")
    assert param.family_id == "nx3"
    assert param.address == 6900
    assert param.format == NextFormat.FLOAT

    param = dataset.get_by_address(1200, "sys")
    assert param.family_id == "sys"
    assert param.address == 1200
    assert param.format == NextFormat.ENUM
    assert param.options != None
    assert type(param.options) is dict

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_address(9999)

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_address(5100, "bat")


def test_id():
    dataset = NextFactory.create_dataset()

    param = dataset.get_by_id(NextDataset.ID_INSTALLATION_GUID)
    assert param.family_id == "sys"
    assert param.address == 2103
    assert param.format == NextFormat.STRING

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_id(None)

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_id("")

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_id("9.9.9.9")

    with pytest.raises(NextDatapointUnknownException):
        param = dataset.get_by_id("dummy")


def test_enum():
    dataset = NextFactory.create_dataset()

    param = dataset.get_by_address(5100)
    assert param.options != None
    assert type(param.options) is dict
    assert len(param.options) == 4

    assert param.enum_value(0) == "No warning(s) or error(s)"
    assert param.enum_value("0") == "No warning(s) or error(s)"
    assert param.enum_value(9) == "9"
    assert param.enum_value("9") == "9"

    assert param.enum_key("No warning(s) or error(s)") == 0
    assert param.enum_key("Unknown") == None
    assert param.enum_key(9) == None
    assert param.enum_key("9") == None


@pytest.mark.parametrize(
    "family_id, exp_len",
    [
        ("sys", 25),
        ("bat", 5),
        ("acs", 8),
        ("acf", 14),
        ("nx3", 26),
        ("nx1", 14),
        ("nxg", 29),
    ]
)
def test_menu(family_id, exp_len):
    dataset = NextFactory.create_dataset()
    
    root_items = dataset.get_menu_items(family_id)
    assert len(root_items) == exp_len

    for item in root_items:
        sub_items = dataset.get_menu_items(family_id, item.id)
        assert len(sub_items) >= 0

