# Do not edit this file directly. It has been autogenerated from
# tests\test_api_async.py
import asyncio
import copy
import pytest
import pytest_asyncio

from datetime import datetime
from pymodbus.pdu import ModbusPDU
from pymodbus.client import AsyncModbusTcpClient, ModbusTcpClient

from pystudernext import AsyncNextFactory, NextFactory
from pystudernext import NextDataType

from . import AsyncNextApiStub, NextApiStub


@pytest.mark.parametrize(
    "name, test_fam, test_slave, test_addr, test_value, test_format, exp_except",
    [
        ("request bool ok",      'sys', 1,  2121, True,   NextDataType.BOOL, None),
        ("request int ok",       'sys', 1,  2122, 1234,   NextDataType.INT, None),
        ("request uint ok",      'nx3', 14, 14,   1234,   NextDataType.UINT, None),
        ("request float ok",     'sys', 1,  3908, 1234.0, NextDataType.FLOAT, None),
        ("request float64 ok",   'sys', 1,  3924, 1234.0, NextDataType.FLOAT64, None),
        ("request string ok",    'sys', 1,  2103, "00112233-4455-6677-8899-aabbccddeeff", NextDataType.STRING, None),
    ]
)
def test_request_value(name, test_fam, test_slave, test_addr, test_value, test_format, exp_except):

    read_called = False
    read_address = None
    read_count = None
    read_slave = None

    def on_read(api: NextApiStub, address: int, count: int, slave: int) -> ModbusPDU:
        """Helper to return the registers for a read"""
        nonlocal read_called
        nonlocal read_address
        nonlocal read_count
        nonlocal read_slave

        read_called = True
        read_address = address
        read_count = count
        read_slave = slave

        data_type = NextDataType.to_datatype(test_format)
        registers = ModbusTcpClient.convert_to_registers(value=test_value, data_type=data_type)

        return ModbusPDU(dev_id=slave, transaction_id=9876, address=address, registers=registers)

    dataset = NextFactory.create_dataset()
    param = dataset.get_by_address(test_addr, test_fam)

    api = NextApiStub(on_read_handler=on_read)

    if exp_except == None:
        rsp_value = api.request_value(param, test_slave)

        assert read_called
        assert read_slave == test_slave
        assert read_address == param.address
        assert read_count == param.size

        assert rsp_value == test_value

    else:
        with pytest.raises(exp_except):
            rsp_value = api.request_value(param, test_slave)


@pytest.mark.parametrize(
    "name, test_fam, test_slave, test_addr, test_value, test_format, exp_except",
    [
        ("request bool ok",      'sys', 1,  2121, True,   NextDataType.BOOL, None),
        ("request int ok",       'sys', 1,  2122, 1234,   NextDataType.INT, None),
        ("request uint ok",      'nx3', 14, 14,   1234,   NextDataType.UINT, None),
        ("request float ok",     'sys', 1,  3908, 1234.0, NextDataType.FLOAT, None),
        ("request float64 ok",   'sys', 1,  3924, 1234.0, NextDataType.FLOAT64, None),
        ("request string ok",    'sys', 1,  2103, "00112233-4455-6677-8899-aabbccddeeff", NextDataType.STRING, None),
    ]
)
def test_write_value(name, test_fam, test_slave, test_addr, test_value, test_format, exp_except):

    write_called = False
    write_address = None
    write_regs = None
    write_slave = None

    def on_write(api: NextApiStub, address: int, regs: list[int], slave: int):
        """Helper to return the registers for a read"""
        nonlocal write_called
        nonlocal write_address
        nonlocal write_regs
        nonlocal write_slave

        write_called = True
        write_address = address
        write_regs = regs
        write_slave = slave

        return ModbusPDU(dev_id=slave, transaction_id=9876, address=address)

    dataset = NextFactory.create_dataset()
    param = dataset.get_by_address(test_addr, test_fam)

    api = NextApiStub(on_write_handler=on_write)

    if exp_except == None:
        rsp_value = api.update_value(param, test_value, test_slave)

        assert write_called
        assert write_slave == test_slave
        assert write_address == param.address
        assert write_regs is not None

        data_type = NextDataType.to_datatype(test_format)
        registers = ModbusTcpClient.convert_to_registers(value=test_value, data_type=data_type)

        assert write_regs == registers

    else:
        with pytest.raises(exp_except):
            rsp_value = api.update_value(param, test_value, test_slave)
 