# Do not edit this file directly. It has been autogenerated from
# src\pystudernext\discover_async.py
"""xcom_api.py: communication api to Studer Xcom via LAN."""

import asyncio
import httpx
import ipaddress
import logging
import os
import struct

from dataclasses import dataclass

from .api_base_async import (
    AsyncNextApi,
)
from .api_base_sync import (
    NextApi,
)
from .const import (
    NextDiscoverNotConnected,
)
from .data import (
    NextDiscoveredDevice,
    NextDiscoveredGateway,
)
from .datapoints import (
    NextDatapoint,
    NextDataset,
    NextDatapointUnknownException,
)
from .families import (
    NextDeviceFamilies
)
import concurrent.futures

_LOGGER = logging.getLogger(__name__)
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("httpcore").setLevel(logging.WARNING)


class AsyncXcomDiscover:

    def __init__(self, api: AsyncNextApi, dataset: NextDataset):
        """
        We connect to the NX Gateway.
        Once it is connected we can send package requests.
        """
        self._api = api
        self._dataset = dataset


    def discover_devices(self, getExtendedInfo = False, verbose = False) -> list[NextDiscoveredDevice]:
        """
        Discover which Studer devices can be reached via the Xcom client
        """
        devices: list[NextDiscoveredDevice] = []

        # Sanity check
        if not self._api.connected:
            raise NextDiscoverNotConnected("NextApi is not connected to remote NX Gateway; please connect first.")
        
        # Check presence of devices for each family
        for family in NextDeviceFamilies.get_list():

            _LOGGER.info(f"Trying family {family.id} ({family.model})")

            # Get value for the specific discovery addr
            addr = family.addr_discover or None
            if not addr:
                continue

            # Iterate all slaves in the family, up to the first slave that is not found
            for device_slave in range(family.slave_devices_start, family.slave_devices_end+1):

                device_code = family.get_code(device_slave)

                # Have we already discovered a device for this address?
                device_found = next((d for d in devices if d.slave == device_slave), None)
                if device_found is not None:
                    # Do not test further device addresses in this family
                    _LOGGER.info(f"  Skip device {device_code}; already found device {device_found.code}")
                    break

                # Send the test request to the device. This will return None in case:
                # - the device does not exist (DEVICE_NOT_FOUND)
                # - the device does not support the param (INVALID_DATA), used to distinguish BSP from BMS
                try:
                    param = self._dataset.get_by_addr(addr, family.id)

                    _LOGGER.info(f"Trying device {device_code} (slave {device_slave}) for addr {addr}")

                    value = self._api.request_value(param, device_slave, verbose=verbose)
                    if value is not None:
                        _LOGGER.info(f"  Found device {device_code}")

                        device = NextDiscoveredDevice(device_code, device_slave, family.id, family.model)
                        if getExtendedInfo:
                            device = self.get_extended_device_info(device, verbose=verbose)
                        
                        devices.append(device)

                    else:
                        _LOGGER.info(f"  No device {device_code}; no value returned from NX Gateway")

                except Exception as e:
                    _LOGGER.info(f"  No device {device_code}; no value returned from NX Gateway: {e}")

                    # Do not test further device addresses in this family
                    break

        return devices


    def get_extended_device_info(self, device: NextDiscoveredDevice, verbose=False) -> NextDiscoveredDevice:
        """
        Rough code taken from pystuderxcom.
        Still needs to have appropriate datapoint names set.
        """
        # ID type
        # ID HW
        # ID HW PWR
        # ID SOFT msb/lsb
        # ID SID
        try:
            _LOGGER.info(f"Trying to get extended device info for device {device.code})")
            family = NextDeviceFamilies.get_by_id(device.family_id)

            id_type    = self._request_value_by_name("ID type",     family.id, device.slave, verbose=verbose)
            id_hw      = self._request_value_by_name("ID HW",       family.id, device.slave, verbose=verbose)
            id_hw_pwr  = self._request_value_by_name("ID HW PWR",   family.id, device.slave, verbose=verbose)
            id_sw_msb  = self._request_value_by_name("ID SOFT msb", family.id, device.slave, verbose=verbose)
            id_sw_lsb  = self._request_value_by_name("ID SOFT lsb", family.id, device.slave, verbose=verbose)

            device.device_model = self._decode_type(id_type, "ID type", family.id)
            device.hw_version   = self._decode_id_hw(id_hw, id_hw_pwr)
            device.sw_version   = self._decode_id_sw(id_sw_msb, id_sw_lsb)

            _LOGGER.info(f"  Found extended device info: model: {device.device_model}, hw_version: {device.hw_version}, sw_version: {device.sw_version}")

        except Exception as e:
            _LOGGER.warning(f"  Exception in getExtendedDeviceInfo: {e}")

        return device


    def _request_value_by_name(self, param_name, family_id, device_slave, verbose=False):
        try:
            param = self._dataset.get_by_name(param_name, family_id)
            return self._api.request_value(param, device_slave, verbose=verbose)
        except:
            # Not all devices have these IDs
            return None
        

    def _decode_type(self, val, param_name, family_id):
        if val is None:
            return None

        param = self._dataset.get_by_name(param_name, family_id)
        return param.options.get(str(int(val)), None) if param.options else None


    def _decode_id_hw(self, cmd, pwr):
        if cmd is None:
            return None
        
        bytes_cmd = struct.pack(">H", int(cmd))
        if pwr is None:
            return f"{int(bytes_cmd[0])}.{int(bytes_cmd[1])}"
        else:
            bytes_pwr = struct.pack(">H", int(pwr))
            return f"{int(bytes_cmd[0])}.{int(bytes_cmd[1])} / {int(bytes_pwr[0])}.{int(bytes_pwr[1])}"


    def _decode_id_sw(self, msb, lsb):
        if msb is None or lsb is None:
            return None
        
        bytes = struct.pack(">H", int(msb)) + struct.pack(">H", int(lsb))
        return f"{int(bytes[0])}.{int(bytes[2])}.{int(bytes[3])}"


    def _decode_fid(self, msb, lsb):
        if msb is None or lsb is None:
            return None
        
        bytes = struct.pack(">H", int(msb)) + struct.pack(">H", int(lsb))
        return bytes.hex(' ',4).upper()


    def discover_gateway_info(self, verbose=False) -> NextDiscoveredGateway:
        """
        Discover extended info about the remote NX Gateway we're connected to
        """

        # Sanity checks
        if not self._api.connected:
            raise NextDiscoverNotConnected("NextApi is not connected to remote NX Gateway; please connect first.")

        if not self._api.remote_ip:
            raise NextDiscoverNotConnected("No IP address was detected for the remote NX Gateway")

        _LOGGER.info(f"Trying to get gateway info")
        gateway_ip = None
        gateway_guid = None

        try:
            gateway_ip = str(ipaddress.ip_address(self._api.remote_ip))

            _LOGGER.info(f"  Found ip: {gateway_ip}")

        except Exception as e:
            _LOGGER.warning(f"  Exception in discoverClientInfo: {e}")

        try:
            gateway_guid = self._api.request_guid(verbose=verbose)

            _LOGGER.info(f"  Found guid: {gateway_guid}")

        except Exception as e:
            _LOGGER.warning(f"  Exception in discover_gateway_info: {e}")

        return NextDiscoveredGateway(
            ip = gateway_ip,
            guid = gateway_guid,
        )


    @staticmethod
    def discover_gateway_webconfig(hint: str = None) -> str:
        """
        Discover if NX Gateway Config page can be found on the local network
        """

        # Find all device IP addresses to check
        urls: list[str] = [hint] if hint else []
        urls.append("http://192.168.127.254")   # default if using static address

        for line in os.popen('arp -a'):     # arp seems to be available on Linux, Windows and Pi
            try:
                # Linux:  
                #   ? (192.168.88.250) at 00:90:e8:3c:f8:7e [ether] on end0
                #   ...
                # Windows: 
                #   Interface: 192.168.88.100 --- 0x4
                #     Internet Address      Physical Address      Type
                #     192.168.88.250        00-90-e8-3c-f8-7e     dynamic 
                #     ...
                
                device = line.strip('?').split()[0].strip('()')
                ip = ipaddress.ip_address(device)
                urls.append(f"http://{str(ip)}")
            except:
                pass

        # Define helper function to check for Moxa Web Config page
        def check_url(client:httpx.Client, url:str) -> str|None:
            _LOGGER.info(f"Trying {url}")
            try:
                rsp = client.get(url)
                if rsp and rsp.is_success and rsp.headers.get("Server", "").startswith("Studer"):
                    return url
                else:
                    return None
            except:
                return None

        # Parallel check for NX Gateway Config page on all found device url's
        # No need to SSL verify plain HTTP GET calls, this also keeps Home Assistant happy
        with httpx.Client(verify=False) as client:
            with concurrent.futures.ThreadPoolExecutor() as executor:
                tasks = [executor.submit(check_url, client, url) for url in urls]

                # Start checking completed tasks immediately. Cancel remaining tasks if our url was found
                for task in concurrent.futures.as_completed(tasks):
                    url = task.result() if hasattr(task, 'result') and callable(task.result) else task
                    if url is not None:
                        for t in tasks:
                            t.cancel()

                        return url
                     
        return None
    
